### ISSUE TITLE
Can you get this to swap IDs for HashIDs?

### ISSUE THREAD

**Issue by Jamesking56** [spatie/laravel-resource-links#18]
It would be really nice to swap the integer IDs for HashIDs instead. Is that possible in this package?

**Comment by rubenvanassche** [comment]
Hi @Jamesking56 ,

That's actually possible!

```php
$links->action([OrdersController::class, 'show'])
    ->parameters(['currentPeriod' => $this->period->getHashId()]);
```

But at the moment it is not possible when you want to overwrite the id of the current model given to the resource. Let's say that the example above sits in an OrderResource which has an Order as model. Then it is possible to overwrite the `currentPeriod` id with an hash id. But the `order` id cannot be overwritten by a hash id due to the first rule of the parameter resolver(https://github.com/spatie/laravel-resource-links/blob/3c326ff56a689b02087a64c486c17e804bbc0f7e/src/ParameterResolver.php#L51). Though that's something we can work out in the future to make it work.
