### ISSUE TITLE
Policy/Guard Support

### ISSUE THREAD

**Issue by sniper7kills** [spatie/laravel-resource-links#27]
Awesome package!

One thing that would really nice to see is some type of policy check before including a link.
I.E. if the current user isn't able to update a post; the link for updating shouldn't be included.

Not sure how hard it would be to implement; but I'll try taking a closer look in the next few weeks.

**Comment by rubenvanassche** [comment]
Hi @sniper7kills,

What we're currently doing at Spatie is providing next to the `endpoints` key in our response a `can` key where we sum up what a user can do for that resource using Laravel's methods:

```php
'can' => [
    'update-posts' => $user->can('update', $post),
]
```

I think it's quite hard to accomplish this or selecting routes based upon policies in the package because we have to match policies to routes, if you have an idea feel free to PR it. I would recommend the use of the `can` array, it's quite elegant in my opinion 😄
